export const SET_CURRENT_USER = 'set-current-user'
export const LOG_OUT = 'log-out'
export const SET_THEME = 'set-theme'
export const SET_ACTIVE_STATUS = 'set-active-status'
export const SET_INCOMING_CALL = 'incoming-call'
