name: Chat App UI Deployment

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy using ssh
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: 22
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /var/www/nextjs/chat-app-ui
                      git fetch origin
                      git checkout main
                      git pull
                      yarn install
                      yarn build
                      pm2 restart chat-app-ui
